version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: 1234
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"

